<?php

acf_add_local_field_group(array(
  'key' => 'acfb_button',
  'title' => 'Block: Button',
  'fields' => array(
		array(
			'key' => 'acfb_button__link',
			'label' => 'Link',
			'name' => 'link',
			'type' => 'link',
			'instructions' => 0,
			'required' => 1,
			'conditional_logic' =>  0,
			'wrapper' => array(
				'width' => '',
				'class' => 'link_field',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'acfb_button__size',
			'label' => 'Size',
			'name' => 'size',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'size_field',
				'id' => '',
			),
			'default_value' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'allow_null' => 0,
			'layout' => 'horizontal',
			'default_value' => 'regular',
			'choices' => array(
				'small' => 'Small',
				'regular' => 'Regular',
				'large' => 'Large',
			),
		),
		array(
			'key' => 'acfb_button__style',
			'label' => 'Style',
			'name' => 'style',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'style_field',
				'id' => '',
			),
			'default_value' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'allow_null' => 0,
			'layout' => 'horizontal',
			'default_value' => 'default',
			'choices' => array(
				'default' => 'Default',
				'blue' => 'Blue',
				'red' => 'Red',
			),
		),
	),
  'location' => array (
      array (
          array (
              'param' => 'block',
              'operator' => '==',
              'value' => 'acf/button',
          ),
      ),
  ),
  "active" => 1,
  'show_in_graphql' => 1,
  "graphql_field_name" => "acfBlockButton",
  "map_graphql_types_from_location_rules" => 1,
));