<?php

	acf_add_local_field_group( array(
	'key' => 'acfb_gallery',
	'title' => 'Block: Gallery',
	'fields' => array(
		array(
			'key' => 'acfb_gallery__images',
			'label' => 'Images',
			'name' => 'images',
			'aria-label' => '',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min' => 2,
			'max' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'insert' => 'append',
			'preview_size' => 'medium',
			'show_in_graphql' => 1,
			'graphql_description' => '',
			'graphql_field_name' => 'gallery',
		),
	),
	'location' => array(
    array (
        array (
            'param' => 'block',
            'operator' => '==',
            'value' => 'acf/gallery',
        ),
    ),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'show_in_graphql' => 1,
	'graphql_field_name' => 'acfBlockGallery',
  "map_graphql_types_from_location_rules" => 1,
) );
