<?php

function bald_child_disable_blocks( $allowed_blocks ) {
	$blocks = WP_Block_Type_Registry::get_instance()->get_all_registered();

	$disabled_blocks = array(
		// 'core/column',
		// 'core/columns',
		// 'core/group',
		// 'core/separator',
		// 'core/spacer',
		// 'core/text-columns',
		// 'core/video',
		// 'core/block',
		// 'core/heading',
		// 'core/list',
		// 'core/list-item',
		// 'core/missing',
		// 'core/paragraph',
		// 'core/pullquote',
		// 'core/quote',
		// 'core/table',
		// 'core/pattern',
		// 'core/html',
		'core/button',
		'core/buttons',
		'core/nextpage',
		'core/freeform',
		'core/calendar',
		'core/comment-template',
		'core/home-link',
		'core/navigation-link',
		'core/navigation-submenu',
		'core/more',
		'core/embed',
		'core/cover',
		'core/file',
		'core/gallery',
		'core/image',
		'core/audio',
		'core/media-text',
		'core/footnotes',
		'core/code',
		'core/details',
		'core/preformatted',
		'core/verse',
		'core/avatar',
		'core/comment-author-name',
		'core/comment-content',
		'core/comment-date',
		'core/comment-edit-link',
		'core/comment-reply-link',
		'core/comments',
		'core/comments-pagination',
		'core/comments-pagination-next',
		'core/comments-pagination-numbers',
		'core/comments-pagination-previous',
		'core/comments-title',
		'core/loginout',
		'core/navigation',
		'core/post-author',
		'core/post-author-biography',
		'core/post-author-name',
		'core/post-comments-form',
		'core/post-content',
		'core/post-date',
		'core/post-excerpt',
		'core/post-featured-image',
		'core/post-navigation-link',
		'core/post-template',
		'core/post-terms',
		'core/post-title',
		'core/query',
		'core/query-no-results',
		'core/query-pagination',
		'core/query-pagination-next',
		'core/query-pagination-numbers',
		'core/query-pagination-previous',
		'core/query-title',
		'core/read-more',
		'core/site-logo',
		'core/site-tagline',
		'core/site-title',
		'core/template-part',
		'core/term-description',
		'core/post-comments',
		'core/legacy-widget',
		'core/widget-group',
		'core/archives',
		'core/categories',
		'core/latest-comments',
		'core/latest-posts',
		'core/page-list',
		'core/page-list-item',
		'core/rss',
		'core/search',
		'core/shortcode',
		'core/social-link',
		'core/tag-cloud',
		'core/social-links',
		'yoast-seo/breadcrumbs',
		'yoast/faq-block',
		'yoast/how-to-block',
	);

	foreach ($disabled_blocks as $disabled_block) {
		unset( $blocks[ $disabled_block ] );
	}

	return array_keys( $blocks );
}
add_filter( 'allowed_block_types_all', 'bald_child_disable_blocks' );